sudo: required
services:
    - docker

before_install:
    - docker build -t sharidasan/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sharidasan/docker-react npm run test -- --coverage
